name: Migrate Secrets

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Install CircleCI CLI
        run: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
      - name: Migrate Secrets
        shell: pwsh
        env:
          AZURE_DNS_CLIENT_ID: ${{ secrets.AZURE_DNS_CLIENT_ID}}
          AZURE_DNS_CLIENT_SECRET: ${{ secrets.AZURE_DNS_CLIENT_SECRET}}
          AZURE_DNS_DOMAIN: ${{ secrets.AZURE_DNS_DOMAIN}}
          AZURE_DNS_SUBSCRIPTION_ID: ${{ secrets.AZURE_DNS_SUBSCRIPTION_ID}}
          AZURE_DNS_TENANT_ID: ${{ secrets.AZURE_DNS_TENANT_ID}}
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN}}
          CLOUDFLAREAPI_ACCOUNTID: ${{ secrets.CLOUDFLAREAPI_ACCOUNTID}}
          CLOUDFLAREAPI_DOMAIN: ${{ secrets.CLOUDFLAREAPI_DOMAIN}}
          CLOUDFLAREAPI_TOKEN: ${{ secrets.CLOUDFLAREAPI_TOKEN}}
          CLOUDNS_AUTH_ID: ${{ secrets.CLOUDNS_AUTH_ID}}
          CLOUDNS_AUTH_PASSWORD: ${{ secrets.CLOUDNS_AUTH_PASSWORD}}
          DIGITALOCEAN_DOMAIN: ${{ secrets.DIGITALOCEAN_DOMAIN}}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN}}
          GANDI_V5_APIKEY: ${{ secrets.GANDI_V5_APIKEY}}
          GANDI_V5_DOMAIN: ${{ secrets.GANDI_V5_DOMAIN}}
          GCLOUD_DOMAIN: ${{ secrets.GCLOUD_DOMAIN}}
          GCLOUD_PRIVATEKEY: ${{ secrets.GCLOUD_PRIVATEKEY}}
          NAMEDOTCOM_DOMAIN: ${{ secrets.NAMEDOTCOM_DOMAIN}}
          NAMEDOTCOM_KEY: ${{ secrets.NAMEDOTCOM_KEY}}
          POWERDNS_APIKEY: ${{ secrets.POWERDNS_APIKEY}}
          POWERDNS_APIURL: ${{ secrets.POWERDNS_APIURL}}
          POWERDNS_DOMAIN: ${{ secrets.POWERDNS_DOMAIN}}
          POWERDNS_SERVERNAME: ${{ secrets.POWERDNS_SERVERNAME}}
          ROUTE53_DOMAIN: ${{ secrets.ROUTE53_DOMAIN}}
          ROUTE53_KEY: ${{ secrets.ROUTE53_KEY}}
          ROUTE53_KEY_ID: ${{ secrets.ROUTE53_KEY_ID}}
        run: |
          circleci setup --no-prompt --token ${{ secrets.CIRCLECI_TOKEN }}
          $secrets = @(
          'AZURE_DNS_CLIENT_ID',
          'AZURE_DNS_CLIENT_SECRET',
          'AZURE_DNS_DOMAIN',
          'AZURE_DNS_SUBSCRIPTION_ID',
          'AZURE_DNS_TENANT_ID',
          'CLOUDFLAREAPI_ACCOUNTID',
          'CLOUDFLAREAPI_DOMAIN',
          'CLOUDFLAREAPI_TOKEN',
          'CLOUDNS_AUTH_ID',
          'CLOUDNS_AUTH_PASSWORD',
          'DIGITALOCEAN_DOMAIN',
          'DIGITALOCEAN_TOKEN',
          'GANDI_V5_APIKEY',
          'GANDI_V5_DOMAIN',
          'GCLOUD_DOMAIN',
          'GCLOUD_PRIVATEKEY',
          'NAMEDOTCOM_DOMAIN',
          'NAMEDOTCOM_KEY',
          'POWERDNS_APIKEY',
          'POWERDNS_APIURL',
          'POWERDNS_DOMAIN',
          'POWERDNS_SERVERNAME',
          'ROUTE53_DOMAIN',
          'ROUTE53_KEY',
          'ROUTE53_KEY_ID')

          foreach ($s in $secrets) {
              [Environment]::GetEnvironmentVariable($s) |
                  circleci context store-secret github StackExchange DNSProviders $s
          }
